### ISSUE TITLE
Undefined name

### ISSUE THREAD

**Issue by skipmeister123** [aloisdeniel/flutter_sheet_localization#19]
I'm going through and trying to implement this for the first time.  I think I've got everything in place, but I get this message:

![image](https://user-images.githubusercontent.com/1911919/83655943-f30de500-a58c-11ea-94fe-01d52beda060.png)

Can you explain what's going on, and offer a suggestion for how to resolve this?

**Comment by aloisdeniel** [comment]
Make sure you have this dependency in your `pubspec.yaml` :

```yaml
dependencies
  flutter_localizations: 
    sdk: flutter
```
