### ISSUE TITLE
After upgrading to NNBD 3.0.0

### ISSUE THREAD

**Issue by salehahmedZ** [aloisdeniel/flutter_sheet_localization#42]
After upgrading package to NNBD 3.0.0
 
I'm seeing the following errors

```
lib/localization.g.dart:47:13: Error: The parameter 'settings' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
    Try adding either an explicit non-'null' default value or the 'required' modifier.
```

Is it because flutter_sheet_localization_generator still not migrated to NNBD?

**Comment by stepanzalis** [comment]
@salehahmedZ Have the same issue, have you resolved this?

**Comment by njovy** [comment]
@salehahmedZ Also having the same issue.

**Comment by salehahmedZ** [comment]
@stepanzalis 
@njovy 

A temporary solution is to use the below git in your project's pubspec.yaml


```yaml
dev_dependencies:
  flutter_sheet_localization_generator: #^3.0.0
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
      ref: nnbd
```

I forked the repo and migrated the generator to NNBD
