### ISSUE TITLE
can someone fork for an active contribution ? then people can contribute ?

### ISSUE THREAD

**Issue by billyandco** [aloisdeniel/flutter_sheet_localization#61]
TODO : 
- upgrade dart to 2.16 (for now)
- upgrade dependencies

not actually working on it, but plan to fork this beautiful project

**Comment by ngockhanhbl** [comment]
same here

**Comment by bobatsar** [comment]
I am now using https://github.com/hacnguyen1412/flutter_sheet_localization
with the following entries in `pubspec.yaml`
```
dependencies:
  flutter_sheet_localization:
      git:
        url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
        path: flutter_sheet_localization

dev_dependencies:
  flutter_sheet_localization_generator: 
      git:
        url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator
```

Thanks @hacnguyen1412 for the fixes in your fork
